### ISSUE TITLE
Please help me，why xrange is not defined

### ISSUE THREAD

**Issue by weiyidounai** [gamboviol/bpr#11]
Traceback (most recent call last):
  File "D:/PycharmProjects/recommendation algorithm/bpr.py", line 289, in <module>
    model.train(data,sampler,num_iters)
  File "D:/PycharmProjects/recommendation algorithm/bpr.py", line 45, in train
    self.init(data)
  File "D:/PycharmProjects/recommendation algorithm/bpr.py", line 62, in init
    self.create_loss_samples()
  File "D:/PycharmProjects/recommendation algorithm/bpr.py", line 70, in create_loss_samples
    self.loss_samples = [t for t in sampler.generate_samples(data, num_loss_samples)]
  File "D:/PycharmProjects/recommendation algorithm/bpr.py", line 70, in <listcomp>
    self.loss_samples = [t for t in sampler.generate_samples(data, num_loss_samples)]
  File "D:/PycharmProjects/recommendation algorithm/bpr.py", line 168, in generate_samples
    for _ in xrange(self.num_samples(self.data.nnz)):
NameError: name 'xrange' is not defined

**Comment by datvp09** [comment]
if you use python 3, use range() instead
